name: .NET CI/CD Pipeline

on:
  workflow_dispatch: # Enables manual run button
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history required for SonarCloud analysis

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-DotNet

      # Install SonarCloud Global Tool
      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      # 1. Begin SonarCloud Analysis
      - name: Begin SonarCloud scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"mayurlabhade_dotnet-ci-cd-demo" \
            /o:"mayurlabhade" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"

      # 2. Build & Test
      - name: dotnet restore
        run: dotnet restore src/MyApi/MyApi.csproj

      - name: dotnet build
        run: dotnet build src/MyApi/MyApi.csproj --configuration Release --no-restore

      - name: dotnet test
        run: dotnet test tests/MyApi.Tests/MyApi.Tests.csproj --configuration Release --verbosity normal

      # 3. End SonarCloud Analysis (Uploads metrics to SonarCloud)
      - name: End SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # 4. Publish & Upload Artifact
      - name: dotnet publish
        run: dotnet publish src/MyApi/MyApi.csproj --configuration Release --output ./publish --no-restore

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mayur-DotNet-Artifact-${{ runner.os }}
          path: ./publish
