name: .NET production CICD

on:
  push:
    branches: [dev, main]
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
