name: Learning_GitHub_Actions
on:
  workflow_dispatch:
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
     - run: echo "This is Scan Job"
     - run: print("This is Scan Job From Python")
       shell: python
     - uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 10.*background:  
